# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Restaurant Solution' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'IQKeyboardManagerSwift'
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'PhoneNumberKit', '~> 1.2'
	pod 'KeychainSwift', '~> 7.0'

  target 'Restaurant SolutionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Restaurant SolutionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
